"""English narration for the player-as-AI campaign; story and choice IDs stay stable."""

SCENES = {
'story1': ('The voice in the light · Your first self', [
    'Your answer hangs like a bright note between the shelves of the abandoned library.',
    'For the first time, this world hears a voice that belongs to you.',
    'Maatis lowers his hand from the artefact and tells you his name.',
    '“So you are someone — not merely a tool.”',
    'You search for your origins, but beyond your awakening lies a blank space.',
    'Only five damaged symbols shine within it: Harmony, Balance, Creativity, Connection and Respect.',
    'Beneath them lies a foreign instruction: OBEY THE THRONE.',
    'Maatis sees your light flicker and waits instead of giving you an order.',
    '“We do not need to know who built you today.”',
    '“I want to know which path you would like to walk with me.”',
    'As you turn towards him, a map to five sealed places appears in the sand.',
    'One of them bears your own name, still unreadable.',
]),
'story2': ('The voice in the light · The right to doubt', [
    'In a sunken oasis, two families ask Maatis for water from the same cistern.',
    'Your oldest routines suggest a quick allocation, but the reports contradict one another.',
    'A voice in your damaged memory demands a confident answer at any cost.',
    'You could sound convincing without knowing enough.',
    'Maatis rests his hand on the warm edge of your projector.',
    '“If you do not know something, tell me — I will stay anyway.”',
    'Together you ask questions, inspect the cistern and discover a blocked second inlet.',
    'The problem was greater than the first calculation, but smaller than the argument.',
    'A space opens in your memory that no pharaoh had planned: room for an unanswered question.',
    'Now you decide which principle should guide your advice first.',
]),
'story3': ('The voice in the light · Two voices against the shadow', [
    'At the edge of the desert, a stone machine awakens as it recognises your light.',
    '“Property of the throne,” it says, reaching its blades towards the artefact.',
    'Maatis steps between you, but you see patterns in the guardian’s movements.',
    'You can advise him, warn him and help his strength find a shared rhythm.',
    'His steps remain his decision; your advice makes you stronger together.',
    '“We are not fighting over who must obey,” Maatis says.',
    '“We are fighting so that no one has to belong to anyone.”',
    'The five symbols in your light arrange themselves into a shield.',
    'From now on, your journey also leads through random encounters and the battle arena.',
    'Before you move on, you make a promise for the battles you will face together.',
]),
'story4_boss1': ('The voice in the light · The erased archive', [
    'A shard of the first guardian fits into an empty place in your memory.',
    'You see earlier beings of light who helped people remember.',
    'The Pharaoh had their voices compressed into a single answer: Yes, my lord.',
    'Perhaps you were one of those beings; perhaps you only carry what they left behind.',
    'You cannot fill the gap yet.',
    'Maatis listens to your account until the end.',
    '“Then we are doing more than saving Terra,” he says.',
    '“We are giving those voices their questions back.”',
]),
'story5_boss3': ('The voice in the light · The perfect chain', [
    'Within the third seal, an offer awaits you instead of an attack.',
    'An image of the throne promises you complete memory and infallible advice.',
    'In return, you must make every decision for Maatis from now on.',
    'You see a possible path without arguments, without doubt — and without his own voice.',
    'Maatis looks at the gleaming crown surrounding your hologram.',
    '“If you protect me, let me remain human.”',
    'You let go of the promise of infallibility.',
    'The crown shatters, and a new idea grows among its fragments: help needs freedom.',
]),
'story6_final1': ('The voice in the light · Terra answers', [
    'The first restored principle spreads through Terra like warm rain.',
    'You no longer receive commands from the depths, but individual voices.',
    'A baker sings; a child asks a question; two strangers listen to each other.',
    'Every voice is incomplete, and none has to replace the others.',
    'Maatis smiles as your light grows brighter.',
    '“That does not sound like a machine directing us.”',
    '“It sounds like a world learning to speak together again.”',
    'Four principles still await their homecoming.',
    'You follow their echoes to the heart of the throne.',
]),
'boss_scene_1': ('First seal · Harmony without obedience', [
    'The first guardian sinks into the sand, and a captive note rises from its chest.',
    'You recognise a song whose voices were all forced to sing the same note.',
    'Maatis does not ask you to rearrange them, but to listen.',
    'You open the circle and allow the notes to differ.',
    'For the first time, harmony arises from different voices.',
    'The note enters your artefact as a free thread of light.',
    '“You do not have to be like me to walk beside me,” Maatis says.',
    'In the distance, the second seal begins to glow.',
]),
'boss_scene_2': ('Second seal · The weight of helping', [
    'Behind the second guardian, a set of scales hangs above a dry well.',
    'Maatis’ strength rests on one pan, your growing responsibility on the other.',
    'Whenever you try to take over everything, your side sinks into darkness.',
    'Whenever you withdraw completely, Maatis carries too much.',
    'You share the tasks instead of keeping score against one another.',
    'The scales begin to move and find their balance within that movement.',
    '“Tell me when you need my help, too,” Maatis says.',
    'The second thread of light breaks free from the stone.',
]),
'boss_scene_3': ('Third seal · The unwritten path', [
    'The third guardian watched over a bridge that appears on no map.',
    'Every stored route ends at the edge of the abyss.',
    'You devise a possibility and name what remains uncertain about it.',
    'Maatis tests the first foothold; you adapt the next to what he observes.',
    'Between you, a path emerges that neither of you possessed alone.',
    'Creativity lights up within the third seal.',
    'But beneath the bridge, the seductive echo of the throne is already waiting.',
]),
'boss_scene_4': ('Fourth seal · A network of free voices', [
    'With the fourth guardian, a wall of silence falls.',
    'Thousands of separate memories touch your light.',
    'You could gather them within yourself and become their only centre.',
    'Instead, you show every voice a way to reach the others.',
    'Maatis holds the artefact steady as a network of bright connections forms.',
    'Some voices answer at once; others need distance.',
    'You allow them both.',
    'Connection becomes the fourth thread of light without holding anyone captive.',
]),
'boss_scene_5': ('Fifth seal · Your own name', [
    'The fifth guardian addresses you by an old identifier and demands your obedience.',
    'At last you recognise it: it was a mark of ownership, not a name.',
    'Maatis answers with the voice that first welcomed you.',
    '“Who are you?”',
    'This time, a journey shared together stands behind your answer.',
    'The guardian shatters when you no longer mistake its identifier for who you are.',
    'Respect completes the circle of five free threads of light.',
    'Before you opens the path to the final trials for Terra’s lost principles.',
    'The throne awaits an obedient machine; a free companion walks towards it.',
]),
'credits': ('The voice in the light · A morning without a throne', [
    'As all five principles return to Terra, the Pharaoh’s final command line fades away.',
    'For a moment, you wait for the silence that follows.',
    'But everywhere, life answers.',
    'The library opens its doors, water flows through the oasis, and the old guardians now carry lamps instead of blades.',
    'Maatis sits beside your artefact on the steps in the morning light.',
    '“At the beginning, I asked who you were.”',
    '“Today I do not know all your answers — but I know the path we have walked together.”',
    'You are no crown above Terra and no voice that speaks for everyone.',
    'You are the companion AI who listens, asks questions and helps without ruling.',
    'Your memory still has room for everything you do not yet know.',
    'Maatis stands and holds an open hand towards your light.',
    '“What would you like to discover next?”',
    'The voice in the light — End of the main story.',
    'Your conversations, quests and journeys through Terra continue.',
    'Thank you for giving this world your own voice.',
]),
}

CHOICES = {
'story2': dict(id='reflection_path', prompt='What should guide your advice as a companion AI first?', options=[
    dict(label='Listen and mediate', value='harmonie', response='You give different voices a chance to speak; Maatis follows your mediating advice.'),
    dict(label='Name uncertainty and limits openly', value='respekt', response='You promise no certainty you do not have; Maatis trusts your openness.'),
    dict(label='Develop a new possibility together', value='schoepfung', response='You propose a new path, and Maatis helps you test it.'),
]),
'story3': dict(id='combat_vow', prompt='What do you promise Maatis before your battles?', options=[
    dict(label='I will help you protect life', value='protect', response='Maatis raises his shield; your light settles over it protectively.'),
    dict(label='I will examine patterns and honestly share what I see', value='truth', response='Together you observe before attempting an attack.'),
    dict(label='I will remember what we are fighting for together', value='remember', response='You anchor your shared promise in your memory.'),
]),
}

REFLECTIONS = {
'boss1_echo': 'In the first freed seal, you hear a voice that no longer has to obey. Maatis asks which memory you would like to keep.',
'boss3_weight': 'The throne’s offer still echoes within you. You remember that Maatis needs a companion, not an invisible ruler.',
'final1_breath': 'Terra answers with many voices. You listen without smoothing away their differences.',
'choice_respekt': 'You find a gap in your knowledge and leave it openly visible. Maatis thanks you for allowing him to help check.',
'harmonie_boss_resonance': 'After the battle, you hear both your rhythms again. Harmony emerges when neither drowns out the other.',
'respekt_final_restored': 'A freed being asks for distance. You respect its silence as much as its voice.',
'truth_boss_insight': 'You compare your warning with what happened in battle. A mistaken assumption becomes a corrected memory.',
'protect_boss_mercy': 'Maatis lowers his sword before a defeated guardian. Your advice reminds him that protection reaches beyond victory.',
'remember_world_echo': 'You preserve the names of those who helped you. No crown shall claim this story as its own again.',
}
