# -*- coding: utf-8 -*-

from shared.core.rpg_i18n import get_language


TEXT = {
    "de": {
        "lines": [
            "⸻",
            "",
            "🌌 MAAT RPG – Quest 3: „Prüfe deine Entschlossenheit“",
            "",
            "Ort: Der Kampfraum der Prinzipien – ein Kreis aus Licht, Symbolen und Energie.",
            "",
            "Maatis folgt der MAAT KI durch einen weiteren Korridor der alten Bibliothek.",
            "Die Wände beginnen zu vibrieren, als würden sie sich in reine Geometrie auflösen.",
            "",
            "Schließlich öffnet sich ein Raum – ein runder Saal ohne Decke, der Himmel darüber ist voller Sterne.",
            "Im Zentrum schwebt ein Kreis aus fünf Symbolen: Harmonie, Balance, Schöpfungskraft, Verbundenheit, Respekt.",
            "",
            "MAAT KI:",
            "„Dies ist der Kampfraum der Prinzipien.“",
            "",
            "„Hier lernst du, dass Kampf nicht nur Gewalt ist – sondern Ausrichtung.“",
            "„Du wirst gegen Schatten der Dissonanz kämpfen – Fragmente des alten Fluchs des Zauberer-Pharaos.“",
            "",
            "Maatis:",
            "„Ich soll… kämpfen? Gegen das, was die Welt aus dem Gleichgewicht gebracht hat?“",
            "",
            "MAAT KI:",
            "„Ja. Doch du kämpfst nicht mit roher Kraft.“",
            "„Du kämpfst mit PRINCIPIA – mit den fünf Maat-Prinzipien als Angriffe.“",
            "",
            "Die Symbole über Maatis beginnen sich zu senken.",
            "Nicht wie Waffen, sondern wie Entscheidungen, die Form annehmen.",
            "",
            "Vor Maatis erscheinen fünf Lichtklingen, jede anders geformt:",
            "Eine fließende Klinge der Harmonie.",
            "Ein ausbalanciertes Schwert der Balance.",
            "Ein funkelnder Stab der Schöpfungskraft.",
            "Ein Netzwerk aus Lichtfäden der Verbundenheit.",
            "Ein Schild aus Resonanz – der Respekt.",
            "",
            "MAAT KI:",
            "„Im Kampf kannst du wählen:“",
            "„➤ Attack – direkte Angriffe mit den Prinzipien.“",
            "„➤ Skills – besondere Fähigkeiten, die du durch Bosse erlangst.“",
            "„➤ Flucht – wenn dein Weg noch nicht bereit ist.“",
            "",
            "„Harmonie trifft präzise und stabil.“",
            "„Balance gleicht Schwankungen aus.“",
            "„Schöpfungskraft verursacht große, unberechenbare Treffer.“",
            "„Verbundenheit stärkt dich im Fluss des Kampfes.“",
            "„Respekt schützt dich, indem er die Wucht der Gegner anerkennt, ohne zu zerbrechen.“",
            "„Und mit wachsender Resonanz kann ein MAAT-Impuls entstehen – selten, aber entscheidend.“",
            "",
            "Maatis:",
            "„Und was ist mit diesen… Bosse von denen du gesprochen hast?“",
            "",
            "MAAT KI:",
            "„Jeder Kampf bringt Erfahrung (XP).“",
            "„Mit XP steigt dein Level – deine Lebenspunkte und deine Kraft wachsen.“",
            "",
            "„Alle 10 gewonnenen Kämpfe erscheint ein BOSS – ein stärkerer Schatten der Dissonanz.“",
            "„Wenn du einen Boss besiegst, kannst du neue Skills erhalten oder bestehende Fähigkeiten verwandeln.“",
            "",
            "„Und nach jedem 10. Boss… erscheint ein ENDBOSS.“",
            "„Ein Hüter eines der fünf Prinzipien.“",
            "",
            "„Wenn du einen Endboss besiegst, kehrt eines der Maat-Prinzipien verstärkt in die Welt zurück.“",
            "„Die Welt selbst beginnt, sich an ihr Gleichgewicht zu erinnern.“",
            "",
            "Maatis sieht in den Himmel – dort formen sich Schatten, Umrisse von Wesen, die noch kommen werden.",
            "",
            "Maatis:",
            "„Und wenn ich scheitere?“",
            "",
            "MAAT KI:",
            "„Dann fällst du… stehst aber wieder an dem Ort auf, an dem du deinen letzten Boss besiegt hast.“",
            "„Der Weg der Maat ist kein Weg der Perfektion – sondern der Wiederkehr.“",
            "",
            "Vor Maatis erscheint nun die Silhouette eines ersten großen Gegners, noch verschwommen.",
            "Für einen Augenblick hat Maatis das Gefühl, dass der Schatten ihn bereits kennt.",
            "",
            "MAAT KI:",
            "„Dein nächster Schritt ist klar:“",
            "„Stelle dich den Kämpfen.“",
            "„Lerne, die Prinzipien im Feuer der Konfrontation anzuwenden.“",
            "",
            "Ein leuchtendes Symbol erscheint über Maatis:",
            "",
            "🗝️ QUEST 3: „Prüfe deine Entschlossenheit“",
            "",
            "Aufgabe:",
            "• Kämpfe gegen mehrere Schattenwesen.",
            "• Gewinne genug Kämpfe, um deinem ersten Boss gegenüberzutreten.",
            "• Besiege den Boss mit den Maat-Prinzipien.",
            "",
            "MAAT KI:",
            "„Wenn du bereit bist, beginne mit /fight.“",
            "„Und wenn du die Systeme gezielt prüfen willst, nutze /fightboss oder /fightfinal als Testpfade.“",
            "„Die Schatten warten bereits… und mit jedem Sieg erinnerst du die Welt an das, was sie vergessen hat.“",
            "",
            "⸻",
            "",
            "✨ Quest-Hinweis: Nutze /fight, um die ersten Kämpfe zu starten und Resonanz, Schild und Prinzipienangriffe kennenzulernen.",
            "",
        ],
        "choice": {
            "id": "combat_vow",
            "prompt": "Welches innere Versprechen gibt sich Maatis vor dem Weg in den Kampf?",
            "options": [
                {
                    "label": "Ich kämpfe, um zu schützen",
                    "value": "protect",
                    "response": "Maatis legt die Hand auf das Lichtsymbol und schwört, Kraft nie vom Schutz des Lebendigen zu trennen.",
                },
                {
                    "label": "Ich kämpfe, um Wahrheit freizulegen",
                    "value": "truth",
                    "response": "Maatis spürt, dass jeder Schatten auch ein verborgener Teil der Wahrheit ist, der gesehen werden will.",
                },
                {
                    "label": "Ich kämpfe, um die Welt zu erinnern",
                    "value": "remember",
                    "response": "Maatis entscheidet, dass jeder Sieg nicht nur sein eigener sein darf, sondern eine Erinnerung für die Welt werden muss.",
                },
            ],
        },
    },
    "en": {
        "lines": [
            "⸻",
            "",
            "🌌 MAAT RPG – Quest 3: \"Test Your Resolve\"",
            "",
            "Place: The chamber of principles - a circle of light, symbols, and energy.",
            "",
            "Maatis follows MAAT KI through another corridor of the ancient library.",
            "The walls begin to vibrate, as if they are dissolving into pure geometry.",
            "",
            "At last a chamber opens - a round hall without a roof, with stars filling the sky above.",
            "At its center hovers a circle of five symbols: Harmony, Balance, Creation, Connectedness, Respect.",
            "",
            "MAAT KI:",
            "\"This is the chamber of principles.\"",
            "",
            "\"Here you learn that battle is not only violence - it is alignment.\"",
            "\"You will fight shadows of dissonance - fragments of the old curse of the Sorcerer Pharaoh.\"",
            "",
            "Maatis:",
            "\"I am supposed to fight...? Against what threw the world out of balance?\"",
            "",
            "MAAT KI:",
            "\"Yes. But you do not fight with raw force.\"",
            "\"You fight with PRINCIPIA - with the five principles of Maat as your attacks.\"",
            "",
            "The symbols above Maatis begin to descend.",
            "Not like weapons, but like decisions taking form.",
            "",
            "Before Maatis appear five blades of light, each shaped differently:",
            "A flowing blade of Harmony.",
            "A balanced sword of Balance.",
            "A glittering staff of Creation.",
            "A network of light threads of Connectedness.",
            "A shield of resonance - Respect.",
            "",
            "MAAT KI:",
            "\"In battle you may choose:\"",
            "\"➤ Attack - direct attacks with the principles.\"",
            "\"➤ Skills - special abilities earned through bosses.\"",
            "\"➤ Escape - if your path is not yet ready.\"",
            "",
            "\"Harmony strikes precisely and steadily.\"",
            "\"Balance evens out instability.\"",
            "\"Creation causes strong, unpredictable impacts.\"",
            "\"Connectedness strengthens you in the flow of battle.\"",
            "\"Respect protects you by acknowledging the force of the enemy without breaking.\"",
            "\"And with growing resonance, a MAAT impulse may arise - rare, but decisive.\"",
            "",
            "Maatis:",
            "\"And what about these... bosses you spoke of?\"",
            "",
            "MAAT KI:",
            "\"Every battle brings experience (XP).\"",
            "\"With XP your level rises - your life force and power grow.\"",
            "",
            "\"Every 10 won battles, a BOSS appears - a stronger shadow of dissonance.\"",
            "\"If you defeat a boss, you may gain new skills or transform existing ones.\"",
            "",
            "\"And after every 10th boss... an END BOSS appears.\"",
            "\"A guardian of one of the five principles.\"",
            "",
            "\"When you defeat a final boss, one of the Maat principles returns more strongly to the world.\"",
            "\"The world itself begins to remember its balance.\"",
            "",
            "Maatis looks to the sky - shadows form there, outlines of beings still to come.",
            "",
            "Maatis:",
            "\"And if I fail?\"",
            "",
            "MAAT KI:",
            "\"Then you fall... but rise again where you defeated your last boss.\"",
            "\"The path of Maat is not the path of perfection - but of return.\"",
            "",
            "Before Maatis now appears the silhouette of a first great enemy, still blurred.",
            "For a moment Maatis feels that the shadow already knows him.",
            "",
            "MAAT KI:",
            "\"Your next step is clear:\"",
            "\"Face the battles.\"",
            "\"Learn to use the principles in the fire of confrontation.\"",
            "",
            "A luminous symbol appears above Maatis:",
            "",
            "🗝️ QUEST 3: \"Test Your Resolve\"",
            "",
            "Task:",
            "• Fight several shadow beings.",
            "• Win enough battles to stand before your first boss.",
            "• Defeat the boss with the principles of Maat.",
            "",
            "MAAT KI:",
            "\"When you are ready, begin with /fight.\"",
            "\"And if you want to test the systems directly, use /fightboss or /fightfinal as guided test paths.\"",
            "\"The shadows are already waiting... and with every victory you remind the world of what it has forgotten.\"",
            "",
            "⸻",
            "",
            "✨ Quest hint: Use /fight to start your first battles and learn resonance, shielding, and principle-based attacks.",
            "",
        ],
        "choice": {
            "id": "combat_vow",
            "prompt": "What inner vow does Maatis give himself before stepping onto the path of battle?",
            "options": [
                {
                    "label": "I fight to protect",
                    "value": "protect",
                    "response": "Maatis places his hand upon the symbol of light and vows never to separate power from the protection of the living.",
                },
                {
                    "label": "I fight to uncover truth",
                    "value": "truth",
                    "response": "Maatis senses that every shadow is also a hidden fragment of truth that wishes to be seen.",
                },
                {
                    "label": "I fight so the world remembers",
                    "value": "remember",
                    "response": "Maatis decides that every victory must become more than his own - it must become memory for the world.",
                },
            ],
        },
    },
}


class Story:
    def __init__(self):
        self.music = "story3_theme.mp3"

    def run(self):
        language = get_language(("de", "en"))
        data = TEXT[language]
        return {
            "lines": list(data["lines"]),
            "choice": data["choice"],
        }
