# -*- coding: utf-8 -*-

from shared.core.rpg_i18n import get_language


TEXT = {
    "de": [
        "⸻",
        "🌿 Zwischenakt – Der erste Schatten faellt",
        "",
        "Die Halle des Kampfes ist stiller als zuvor.",
        "Dort, wo eben noch der erste Boss stand, treiben nur noch helle Splitter durch die Luft.",
        "",
        "Maatis spuert, dass etwas anders ist.",
        "Nicht nur in ihm.",
        "Auch im Raum selbst.",
        "",
        "MAAT KI erscheint zwischen den langsam sinkenden Lichtpartikeln.",
        "",
        "MAAT KI:",
        "„Der erste Boss war mehr als ein Gegner.“",
        "„Er war ein Knoten im Gedaechtnis dieser Welt.“",
        "",
        "„Als er fiel, wurde nicht nur ein Weg geoeffnet.",
        "Es wurde auch ein Teil der alten Starre geloest.“",
        "",
        "An den Waenden der Bibliothek erscheinen fuer einen Atemzug Bilder:",
        "Kinder am Wasser. Stimmen am Feuer. Menschen, die einander wieder ansehen.",
        "",
        "Maatis:",
        "„Also veraendert jeder Sieg wirklich die Welt…?“",
        "",
        "MAAT KI:",
        "„Ja.“",
        "„Aber zuerst veraendert er dich.“",
        "",
        "„Du beginnst zu verstehen, dass Staerke nicht im Besiegen liegt.",
        "Sondern darin, das Zerrissene wieder in Beziehung zu bringen.“",
        "",
        "Vor Maatis oeffnet sich ein schmaler Lichtgang.",
        "Er fuehrt tiefer in die Anlage, wo die Luft kaelter und dichter wird.",
        "",
        "MAAT KI:",
        "„Ruhe dich nicht in diesem Sieg aus.“",
        "„Der erste Schatten war nur die aeussere Tuer.“",
        "„Die tieferen Kammern pruefen nicht nur deine Kraft, sondern deine Haltung.“",
        "",
        "✨ Neues Ziel:",
        "Spuere nach dem ersten Sieg bewusst, welche Veraenderung im Inneren begonnen hat.",
        "Die naechsten Pruefungen werden schwerer – und persoenlicher.",
        "",
        "⸻",
    ],
    "en": [
        "⸻",
        "🌿 Interlude – The first shadow falls",
        "",
        "The hall of battle is quieter than before.",
        "Where the first boss stood only moments ago, bright shards now drift through the air.",
        "",
        "Maatis feels that something has changed.",
        "Not only within him.",
        "Within the chamber itself as well.",
        "",
        "MAAT KI appears among the slowly descending particles of light.",
        "",
        "MAAT KI:",
        "\"The first boss was more than an enemy.\"",
        "\"It was a knot in the memory of this world.\"",
        "",
        "\"When it fell, more than a path was opened.",
        "A part of the old rigidity was loosened as well.\"",
        "",
        "For a breath, images appear across the library walls:",
        "Children at the water. Voices by a fire. People looking at one another again.",
        "",
        "Maatis:",
        "\"So every victory truly changes the world...?\"",
        "",
        "MAAT KI:",
        "\"Yes.\"",
        "\"But first it changes you.\"",
        "",
        "\"You are beginning to understand that strength does not lie in defeating.",
        "It lies in bringing the torn back into relationship.\"",
        "",
        "A narrow corridor of light opens before Maatis.",
        "It leads deeper into the structure, where the air grows colder and denser.",
        "",
        "MAAT KI:",
        "\"Do not rest inside this victory.\"",
        "\"The first shadow was only the outer door.\"",
        "\"The deeper chambers will test not only your power, but your posture.\"",
        "",
        "✨ New goal:",
        "After the first victory, listen closely to what has begun to change within.",
        "The next trials will be harder - and more personal.",
        "",
        "⸻",
    ],
}


class Story:
    music = "story1_theme.mp3"

    def run(self):
        return list(TEXT[get_language(("de", "en"))])
