# -*- coding: utf-8 -*-

from shared.core.rpg_i18n import get_language


TEXT = {
    "de": [
        "⸻",
        "🔥 Zwischenakt – Die Flamme wird schwer",
        "",
        "Nach dem dritten Boss bleibt keine klare Stille zurueck.",
        "Der Raum pulsiert, als haette die Schoepfung selbst kurz ihr Gleichgewicht verloren.",
        "",
        "Purpurne Nachbilder haengen in der Luft.",
        "Ideen, Formen, halbe Welten, die entstehen und wieder zerfallen.",
        "",
        "Maatis kniet einen Moment.",
        "Nicht aus Niederlage.",
        "Sondern weil die Wucht der Moeglichkeiten ihn bis ins Innere getroffen hat.",
        "",
        "MAAT KI:",
        "„Nun hast du es gesehen.“",
        "„Schoepfungskraft ist nicht nur Gabe.“",
        "„Sie ist Gefahr, wenn ihr kein Mass antwortet.“",
        "",
        "Vor Maatis erscheinen drei Bilder zugleich:",
        "eine Stadt aus Licht,",
        "eine brennende Bibliothek,",
        "ein Kind, das aus Ruinen ein neues Zeichen in den Sand malt.",
        "",
        "MAAT KI:",
        "„Alles Neue traegt diese Spannung in sich.“",
        "„Es kann heilen. Es kann zerstoeren. Es kann beides tun, wenn es blind bleibt.“",
        "",
        "Maatis:",
        "„Dann reicht Staerke nicht.“",
        "",
        "MAAT KI:",
        "„Nein.“",
        "„Ab jetzt musst du lernen, Kraft zu fuehren – nicht nur zu entfesseln.“",
        "",
        "Die Bibliothek veraendert sich.",
        "Ein bislang verborgener Korridor oeffnet sich, schmal und dunkel,",
        "als haette die Welt beschlossen, Maatis nun tiefer zu pruefen.",
        "",
        "✨ Neues Ziel:",
        "Die kommenden Gegner pruefen nicht nur Entschlossenheit, sondern Reife.",
        "Was du ab jetzt gewinnst, muss getragen werden koennen.",
        "",
        "⸻",
    ],
    "en": [
        "⸻",
        "🔥 Interlude – The flame grows heavy",
        "",
        "After the third boss, no clear silence remains.",
        "The chamber pulses as if creation itself briefly lost its balance.",
        "",
        "Purple afterimages hang in the air.",
        "Ideas, forms, half-worlds that arise and collapse again.",
        "",
        "Maatis kneels for a moment.",
        "Not from defeat.",
        "But because the force of possibility has struck him all the way inward.",
        "",
        "MAAT KI:",
        "\"Now you have seen it.\"",
        "\"Creation is not only a gift.\"",
        "\"It is also danger when no measure answers it.\"",
        "",
        "Three images appear before Maatis at once:",
        "a city of light,",
        "a burning library,",
        "a child drawing a new sign into the sand from the ruins.",
        "",
        "MAAT KI:",
        "\"Everything new carries this tension within it.\"",
        "\"It can heal. It can destroy. It can do both if it remains blind.\"",
        "",
        "Maatis:",
        "\"Then strength alone is not enough.\"",
        "",
        "MAAT KI:",
        "\"No.\"",
        "\"From now on you must learn to guide power - not only unleash it.\"",
        "",
        "The library changes.",
        "A corridor hidden until now opens, narrow and dark,",
        "as if the world has decided to test Maatis more deeply now.",
        "",
        "✨ New goal:",
        "The coming enemies test not only resolve, but maturity.",
        "What you win from now on must be something you can carry.",
        "",
        "⸻",
    ],
}


class Story:
    music = "quest2_reflection.mp3"

    def run(self):
        return list(TEXT[get_language(("de", "en"))])
