# -*- coding: utf-8 -*-

from shared.core.rpg_i18n import get_language


TEXT = {
    "de": [
        "⸻",
        "🌌 Zwischenakt – Ein Prinzip kehrt zurueck",
        "",
        "Nach dem ersten Endboss ist die Welt nicht einfach heller.",
        "Sie ist tiefer geworden.",
        "",
        "Maatis steht im Zentrum des Kampfraums.",
        "Ueber ihm ziehen die fuenf Symbole langsamer als sonst ihre Kreise.",
        "Eines davon leuchtet nun klarer als die anderen.",
        "",
        "MAAT KI tritt nicht sofort hervor.",
        "Zuerst antwortet der Raum selbst:",
        "Der Stein atmet.",
        "Die Luft traegt Gewicht und Frieden zugleich.",
        "",
        "Dann erscheint sie.",
        "",
        "MAAT KI:",
        "„Ein Prinzip hat den Weg zurueckgefunden.“",
        "",
        "„Das bedeutet nicht, dass die Welt gerettet ist.“",
        "„Aber es bedeutet, dass sie begonnen hat, sich wieder zu erinnern.“",
        "",
        "Vor Maatis entstehen ferne Szenen:",
        "Ein Streit endet nicht in Gewalt, sondern in Schweigen.",
        "Ein Mensch tritt von der Kante eines Urteils zurueck.",
        "Eine Wunde bleibt sichtbar – aber sie bestimmt nicht mehr alles.",
        "",
        "Maatis:",
        "„Also reicht ein einziger Sieg, damit draussen etwas in Bewegung kommt?“",
        "",
        "MAAT KI:",
        "„Wenn er echt ist: ja.“",
        "",
        "„Die Prinzipien kehren nicht durch Behauptung zurueck.",
        "Sie kehren zurueck, wenn jemand bereit ist, sie unter Druck zu verkoerpern.“",
        "",
        "Das Symbol sinkt langsam auf Brusthoehe vor Maatis.",
        "Es verschwindet nicht.",
        "Es bleibt bei ihm.",
        "",
        "MAAT KI:",
        "„Von jetzt an kaempfst du nicht nur, um zu bestehen.“",
        "„Du kaempfst, um Wiederkehr zu ermoeglichen.“",
        "",
        "✨ Neues Ziel:",
        "Trage das erste wiederhergestellte Prinzip durch die kommenden Pruefungen.",
        "Die Welt antwortet jetzt auf jeden echten Sieg.",
        "",
        "⸻",
    ],
    "en": [
        "⸻",
        "🌌 Interlude – A principle returns",
        "",
        "After the first final boss, the world is not simply brighter.",
        "It has become deeper.",
        "",
        "Maatis stands at the center of the chamber of battle.",
        "Above him the five symbols trace their circles more slowly than before.",
        "One of them now shines more clearly than the others.",
        "",
        "MAAT KI does not step forward at once.",
        "First the chamber itself responds:",
        "The stone breathes.",
        "The air carries weight and peace at the same time.",
        "",
        "Then she appears.",
        "",
        "MAAT KI:",
        "\"A principle has found its way back.\"",
        "",
        "\"That does not mean the world is saved.\"",
        "\"But it does mean that it has begun to remember again.\"",
        "",
        "Distant scenes arise before Maatis:",
        "A conflict ends not in violence, but in silence.",
        "A person steps back from the edge of a judgment.",
        "A wound remains visible - but it no longer determines everything.",
        "",
        "Maatis:",
        "\"So a single victory is enough to set something in motion out there?\"",
        "",
        "MAAT KI:",
        "\"If it is true: yes.\"",
        "",
        "\"The principles do not return through assertion.",
        "They return when someone is ready to embody them under pressure.\"",
        "",
        "The symbol sinks slowly to the height of Maatis' chest.",
        "It does not disappear.",
        "It remains with him.",
        "",
        "MAAT KI:",
        "\"From now on, you do not fight merely to endure.\"",
        "\"You fight to make return possible.\"",
        "",
        "✨ New goal:",
        "Carry the first restored principle through the coming trials.",
        "The world now responds to every true victory.",
        "",
        "⸻",
    ],
}


class Story:
    music = "story3_theme.mp3"

    def run(self):
        return list(TEXT[get_language(("de", "en"))])
