# -*- coding: utf-8 -*-


class Story:
    music = "story3_theme.mp3"

    def run(self):
        return [
            "⸻",
            "🌌 Zwischenakt – Ein Prinzip kehrt zurück",
            "",
            "Nach dem ersten Endboss ist die Welt nicht einfach heller.",
            "Sie ist tiefer geworden.",
            "",
            "Maatis steht im Zentrum des Kampfraums.",
            "Über ihm ziehen die fünf Symbole langsamer als sonst ihre Kreise.",
            "Eines davon leuchtet nun klarer als die anderen.",
            "",
            "MAAT KI tritt nicht sofort hervor.",
            "Zuerst antwortet der Raum selbst:",
            "Der Stein atmet.",
            "Die Luft trägt Gewicht und Frieden zugleich.",
            "",
            "Dann erscheint sie.",
            "",
            "MAAT KI:",
            "„Ein Prinzip hat den Weg zurückgefunden.“",
            "",
            "„Das bedeutet nicht, dass die Welt gerettet ist.“",
            "„Aber es bedeutet, dass sie begonnen hat, sich wieder zu erinnern.“",
            "",
            "Vor Maatis entstehen ferne Szenen:",
            "Ein Streit endet nicht in Gewalt, sondern in Schweigen.",
            "Ein Mensch tritt von der Kante eines Urteils zurück.",
            "Eine Wunde bleibt sichtbar – aber sie bestimmt nicht mehr alles.",
            "",
            "Maatis:",
            "„Also reicht ein einziger Sieg, damit draußen etwas in Bewegung kommt?“",
            "",
            "MAAT KI:",
            "„Wenn er echt ist: ja.“",
            "",
            "„Die Prinzipien kehren nicht durch Behauptung zurück.",
            "Sie kehren zurück, wenn jemand bereit ist, sie unter Druck zu verkörpern.“",
            "",
            "Das Symbol sinkt langsam auf Brusthöhe vor Maatis.",
            "Es verschwindet nicht.",
            "Es bleibt bei ihm.",
            "",
            "MAAT KI:",
            "„Von jetzt an kämpfst du nicht nur, um zu bestehen.“",
            "„Du kämpfst, um Wiederkehr zu ermöglichen.“",
            "",
            "✨ Neues Ziel:",
            "Trage das erste wiederhergestellte Prinzip durch die kommenden Prüfungen.",
            "Die Welt antwortet jetzt auf jeden echten Sieg.",
            "",
            "⸻",
        ]
