# -*- coding: utf-8 -*-


class Story:
    music = "story1_theme.mp3"

    def run(self):
        return [
            "⸻",
            "🌿 Zwischenakt – Der erste Schatten fällt",
            "",
            "Die Halle des Kampfes ist stiller als zuvor.",
            "Dort, wo eben noch der erste Boss stand, treiben nur noch helle Splitter durch die Luft.",
            "",
            "Maatis spürt, dass etwas anders ist.",
            "Nicht nur in ihm.",
            "Auch im Raum selbst.",
            "",
            "MAAT KI erscheint zwischen den langsam sinkenden Lichtpartikeln.",
            "",
            "MAAT KI:",
            "„Der erste Boss war mehr als ein Gegner.“",
            "„Er war ein Knoten im Gedächtnis dieser Welt.“",
            "",
            "„Als er fiel, wurde nicht nur ein Weg geöffnet.",
            "Es wurde auch ein Teil der alten Starre gelöst.“",
            "",
            "An den Wänden der Bibliothek erscheinen für einen Atemzug Bilder:",
            "Kinder am Wasser. Stimmen am Feuer. Menschen, die einander wieder ansehen.",
            "",
            "Maatis:",
            "„Also verändert jeder Sieg wirklich die Welt…?“",
            "",
            "MAAT KI:",
            "„Ja.“",
            "„Aber zuerst verändert er dich.“",
            "",
            "„Du beginnst zu verstehen, dass Stärke nicht im Besiegen liegt.",
            "Sondern darin, das Zerrissene wieder in Beziehung zu bringen.“",
            "",
            "Vor Maatis öffnet sich ein schmaler Lichtgang.",
            "Er führt tiefer in die Anlage, wo die Luft kälter und dichter wird.",
            "",
            "MAAT KI:",
            "„Ruhe dich nicht in diesem Sieg aus.“",
            "„Der erste Schatten war nur die äußere Tür.“",
            "„Die tieferen Kammern prüfen nicht nur deine Kraft, sondern deine Haltung.“",
            "",
            "✨ Neues Ziel:",
            "Spüre nach dem ersten Sieg bewusst, welche Veränderung im Inneren begonnen hat.",
            "Die nächsten Prüfungen werden schwerer – und persönlicher.",
            "",
            "⸻",
        ]
